#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

[ -n "$CI" ] && exit 0

exec git diff --cached --name-only | npx cspell lint "**" ".**/**" --show-suggestions --no-summary --no-progress --no-must-find-files --config ".vscode/cspell.json" --file-list stdin

npx lint-staged
